@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(usersSystem, "Users System", "Software system", "Handles users personal pages")
Container(postsSystem, "Posts System", "Software system", "Stores information about users posts")
Container(commentsSystem, "Comments System", "Software system", "Stores information about comments to users posts")
Container(followsSystem, "Follows System", "Software system", "Stores information about users followers and followings")
Container(likesSystem, "Likes System", "Software system", "Stores information about reactions on users post")
Container(mediaSystem, "Media System", "Software system", "Stores information about posts media")

Rel(user, usersSystem, "Gets others users information")
Rel(user, postsSystem, "Gets others users posts")
Rel(user, commentsSystem, "Gets others users posts comments")
Rel(user, followsSystem, "Gets information about users followers or followings")
Rel(user, likesSystem, "Gets reactions on users post")
Rel(user, mediaSystem, "Gets users posts media")
@enduml