@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "A user of the social media platform")

Container(loadBalancer, "Load Balancer", "Nginx", "Distributes incoming requests using round robin")

System_Boundary(likesSystem, "Likes System") {
    Container(likesService, "Likes Service", "Go", "Handles posts likes", $tags="webApp")
    ContainerDb(likesDatabase, "Likes Database", "PostgreSQL", "Stores likes information", $tags="db")
}

Container_Boundary(externalSystems, "External Systems") {
    Container(usersSystem, "Users System", "Software System", "Handles users information")
    Container(postsSystem, "Posts System", "Software System", "Stores information about users posts")
}

ContainerQueue(messageQueue, "Events Queue", "Apache Kafka", "Handles events related to likes")

Rel(user, loadBalancer, "Uses", "REST Request")
Rel(loadBalancer, likesService, "Forwards requests to", "REST")

Rel(likesService, likesDatabase, "Reads/Writes likes data", "SQL")
Rel(likesService, messageQueue, "Publishes `like_by_post_event.create`", "Kafka")

Rel(likesService, usersSystem, "Get users base info", "gRPC")
Rel(likesService, postsSystem, "Pass info about likes", "gRPC")

Rel(postsSystem, messageQueue, "Consumes `like_by_post_event.create`", "Kafka")

@enduml